
services:
  nginx:
    image: nginx:latest
    ports:
      - "8012:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./api:/var/www/html
    depends_on:
      - php
      - mysql

  php:
    build:
      context: ./docker/php
    volumes:
      - ./api:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: yourdatabase
      MYSQL_USER: youruser
      MYSQL_PASSWORD: yourpassword
    ports:
      - "3312:3306"
    volumes:
      - ./docker/mysql/example.sql:/docker-entrypoint-initdb.d/example.sql